import {chromium} from '@playwright/test';
import {createServer} from 'vite';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const server=await createServer({server:{host:'127.0.0.1',port:5181}});await server.listen();let browser;
try{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[],missing=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});page.on('response',r=>{if(r.status()===404)missing.push(r.url());});
 await page.goto('http://127.0.0.1:5181');await page.waitForFunction(()=>window.__SURVIVOR_GAME__?.scene.isActive('Menu'));await page.keyboard.press('Enter');await page.waitForFunction(()=>window.__SURVIVOR_GAME__.scene.isActive('CharacterSelect'));await page.keyboard.press('Enter',{delay:100});await page.waitForFunction(()=>window.__SURVIVOR_GAME__.scene.isActive('Game'));
 const initial=await page.evaluate(()=>{const s=window.__SURVIVOR_GAME__.scene.getScene('Game');s.paused=true;s.physics.pause();s.player.invulnerable=999;return {map:s.mapManager.definition.id,start:[s.player.x,s.player.y],world:[s.physics.world.bounds.width,s.physics.world.bounds.height],camera:[s.cameras.main.getBounds().width,s.cameras.main.getBounds().height],fog:s.mapManager.view.fog.length,wisps:s.mapManager.view.wisps.length,staticCount:s.mapManager.view.staticObjects.length,objects:s.children.list.filter(o=>o.name?.startsWith('map:')).length,textures:s.textures.list&&Object.keys(s.textures.list).filter(k=>k.startsWith('mv-')).length,title:s.children.list.filter(o=>o.type==='Text').some(o=>o.text==='월하촌')};});
 assert.equal(initial.map,'moonlit-village');assert.deepEqual(initial.world,[3600,3600]);assert.deepEqual(initial.camera,[3600,3600]);assert.equal(initial.fog,8);assert.equal(initial.wisps,12);assert.ok(initial.staticCount>200&&initial.title);
 fs.mkdirSync('map-previews',{recursive:true});await page.waitForTimeout(200);await page.screenshot({path:'map-previews/start.png'});
 const spots=[['village',1800,2400],['homes',1180,2180],['jangseung',2090,1710],['cemetery',2750,1100],['shrine',1500,850],['seal',1660,1180]];
 for(const [id,x,y] of spots){await page.evaluate(({x,y})=>{const s=window.__SURVIVOR_GAME__.scene.getScene('Game');s.player.setPosition(x,y);s.player.move(0,0,0);s.player.setAlpha(1);s.cameras.main.stopFollow();s.cameras.main.centerOn(x,y);s.mapManager.view.update(3);},{x,y});await page.waitForTimeout(450);await page.evaluate(()=>window.__SURVIVOR_GAME__.scene.getScene('Game').mapManager.view.update(.3));await page.screenshot({path:`map-previews/${id}.png`});}
 const bounds=await page.evaluate(()=>{const s=window.__SURVIVOR_GAME__.scene.getScene('Game');s.player.setPosition(20,20);s.player.move(0,0,0);s.player.setAlpha(1);return {collides:s.player.body.collideWorldBounds,cameraBounds:s.cameras.main.getBounds().width};});assert.ok(bounds.collides&&bounds.cameraBounds===3600);
 await page.evaluate(()=>{const s=window.__SURVIVOR_GAME__.scene.getScene('Game');s.player.setPosition(1800,2400);s.cameras.main.startFollow(s.player,true,.12,.12);s.player.invulnerable=999;s.paused=false;s.physics.resume();});await page.keyboard.down('D');await page.waitForFunction(()=>window.__SURVIVOR_GAME__.scene.getScene('Game').player.x>1800);await page.keyboard.up('D');
 const encounters=await page.evaluate(async()=>{const s=window.__SURVIVOR_GAME__.scene.getScene('Game'),{isMapSpawnSafe}=await import('/src/maps/spawnSafety.ts');s.physics.pause();s.paused=false;s.weapons.update=()=>{};for(const e of s.enemies.items)if(e.active)e.disableBody(true,true);s.elapsed=119.999;s.update(0,16);const elite=s.enemies.items.find(e=>e.active&&e.rank==='elite');const eliteSafe=isMapSpawnSafe(elite.x,elite.y,75);s.elapsed=299.999;s.update(0,16);const general=s.bosses.activeBosses[0],generalSafe=isMapSpawnSafe(general.x,general.y,75),generalMood=s.mapManager.view.mood;s.elapsed=599.999;s.update(0,16);const king=s.bosses.activeBosses.find(b=>b.definition.id==='ghost-king'),kingSafe=isMapSpawnSafe(king.x,king.y,75),kingMood=s.mapManager.view.mood;s.mapManager.update(1,['ghost-king'],false);s.paused=true;return {eliteSafe,generalSafe,kingSafe,generalMood,kingMood,notEnded:!s.ended};});
 assert.ok(encounters.eliteSafe&&encounters.generalSafe&&encounters.kingSafe&&encounters.notEnded);assert.equal(encounters.generalMood,'general');assert.equal(encounters.kingMood,'king');
 await page.evaluate(()=>{const s=window.__SURVIVOR_GAME__.scene.getScene('Game');s.player.setPosition(1660,1180);s.player.move(0,0,0);s.player.setAlpha(1);s.cameras.main.stopFollow();s.cameras.main.centerOn(1660,1180);});await page.waitForTimeout(400);await page.evaluate(()=>window.__SURVIVOR_GAME__.scene.getScene('Game').mapManager.update(.3,['ghost-king'],false));await page.screenshot({path:'map-previews/king-seal.png'});
 const spawn=await page.evaluate(async()=>{const s=window.__SURVIVOR_GAME__.scene.getScene('Game'),{isMapSpawnSafe}=await import('/src/maps/spawnSafety.ts');s.player.setPosition(1190,2030);s.player.invulnerable=999;s.paused=false;for(const e of s.enemies.items)if(e.active&&e.rank==='normal')e.disableBody(true,true);s.spawn.update(10,300,1190,2030);for(const state of s.bosses.states){state.summon=0;}s.bosses.update(.01);s.bosses.update(.9);s.paused=true;return {safe:s.enemies.items.filter(e=>e.active&&e.rank==='normal').every(e=>isMapSpawnSafe(e.x,e.y,45)),gatesSafe:s.bosses.gates.filter(g=>g.life>0).every(g=>isMapSpawnSafe(g.image.x,g.image.y,45))};});assert.ok(spawn.safe&&spawn.gatesSafe);
 const performanceResult=await page.evaluate(()=>{const s=window.__SURVIVOR_GAME__.scene.getScene('Game');for(let i=0;i<350;i++){const a=i*2.39996;s.enemies.acquire()?.spawn(s.player.x+Math.cos(a)*300,s.player.y+Math.sin(a)*300,['grunt','runner','tank'][i%3],100,0);}s.player.invulnerable=999;const costs=[];for(let i=0;i<400;i++){const t=performance.now();s.mapManager.update(.016,['ghost-king'],false);costs.push(performance.now()-t);}costs.sort((a,b)=>a-b);return {mapUpdateP95Ms:costs[Math.floor(costs.length*.95)],mapUpdateMaxMs:Math.max(...costs),enemies:s.enemies.items.filter(e=>e.active).length,visibleTerrainChunks:s.children.list.filter(o=>o.name==='map:terrain'&&o.visible).length};});assert.ok(performanceResult.mapUpdateP95Ms<3&&performanceResult.enemies>=350);
 // Same camera/swarm: compare frame time with map visible and hidden in this renderer.
 await page.evaluate(()=>{const s=window.__SURVIVOR_GAME__.scene.getScene('Game');s.mapManager.view.update(.3);});
 const frameTimes=()=>page.evaluate(async()=>{for(let i=0;i<12;i++)await new Promise(requestAnimationFrame);const times=[];let prev=performance.now();for(let i=0;i<60;i++){await new Promise(requestAnimationFrame);const now=performance.now();times.push(now-prev);prev=now;}times.sort((a,b)=>a-b);return {median:times[30],p95:times[57]};});
 const rendered=await frameTimes();await page.evaluate(async()=>{const s=window.__SURVIVOR_GAME__.scene.getScene('Game');s.__mapVisibility=s.children.list.map(o=>[o,o.visible]);for(const o of s.children.list)if(o.depth<0)o.setVisible(false);const before=new Set(s.children.list);s.add.tileSprite(1800,1800,3600,3600,'grid').setDepth(-10);const marks=s.add.graphics().lineStyle(3,0xb8a16a,.12),{talisman}=await import('/src/theme/ornaments.ts'),{addWorldProps}=await import('/src/theme/worldProps.ts');for(let y=400;y<3600;y+=800)for(let x=400;x<3600;x+=800)talisman(marks,x-20,y-40,40,80,0x594738);addWorldProps(s,3600);s.__baseline=s.children.list.filter(o=>!before.has(o));});const hidden=await frameTimes();await page.evaluate(()=>{const s=window.__SURVIVOR_GAME__.scene.getScene('Game');for(const [o,v] of s.__mapVisibility)o.setVisible(v);delete s.__mapVisibility;for(const o of s.__baseline)o.destroy();delete s.__baseline;});
 // Real combat textures above scenery, both base and evolved weapons with actual hits.
 const combat=await page.evaluate(async()=>{const s=window.__SURVIVOR_GAME__.scene.getScene('Game'),{WeaponSystem}=await import('/src/weapons/WeaponSystem.ts'),{WEAPON_IDS}=await import('/src/data/weaponConfig.ts'),{WEAPON_EVOLUTIONS}=await import('/src/weapons/evolution/weaponEvolutionDefinitions.ts');for(const e of s.enemies.items)if(e.active)e.disableBody(true,true);s.player.setPosition(1800,2400);s.player.move(0,0,0);s.player.setAlpha(1);s.cameras.main.centerOn(1800,2400);const bench=new WeaponSystem(s,s.player,s.enemies,s.bolts,()=>{},()=>{});for(const id of WEAPON_IDS)while(bench.loadout.upgrade(id)){}bench.syncLoadout();const enemies=[];for(let i=0;i<12;i++){const a=i*Math.PI/6,e=s.enemies.acquire();e.spawn(s.player.x+Math.cos(a)*120,s.player.y+Math.sin(a)*120,['grunt','runner','tank'][i%3],100,0);enemies.push(e);}const hitBefore=enemies.reduce((n,e)=>n+e.hp,0);for(let i=0;i<10;i++)bench.update(.1);const baseHit=enemies.reduce((n,e)=>n+e.hp,0)<hitBefore;for(const evo of WEAPON_EVOLUTIONS)bench.loadout.replaceWeapon(evo.baseWeaponId,evo.evolvedWeaponId);bench.syncLoadout();for(let i=0;i<4;i++)bench.update(.1);s.__mapBench=bench;for(let i=0;i<8;i++)s.orbs.acquire()?.spawn(1720+i*35,2530,2);s.mapManager.update(.3,[],false);return {baseHit,orbDepth:s.orbs.items.find(o=>o.active).depth,wispDepth:s.mapManager.view.wisps[0].image.depth,fogDepth:s.mapManager.view.fog[0].image.depth,playerDepth:s.player.depth};});assert.ok(combat.baseHit&&combat.orbDepth>combat.wispDepth&&combat.orbDepth>combat.fogDepth&&combat.playerDepth>combat.orbDepth);
 await page.waitForTimeout(450);await page.evaluate(()=>window.__SURVIVOR_GAME__.scene.getScene('Game').mapManager.update(.3,[],false));await page.screenshot({path:'map-previews/combat.png'});await page.evaluate(()=>{const s=window.__SURVIVOR_GAME__.scene.getScene('Game');s.__mapBench.destroy();delete s.__mapBench;s.mapManager.bossDefeated('ghost-king');});assert.equal(await page.evaluate(()=>window.__SURVIVOR_GAME__.scene.getScene('Game').mapManager.view.mood),'sealed');
 await page.evaluate(()=>window.__SURVIVOR_GAME__.scene.getScene('Game').finish(false));await page.waitForFunction(()=>window.__SURVIVOR_GAME__.scene.isActive('GameOver'));await page.keyboard.press('Enter');await page.waitForFunction(()=>window.__SURVIVOR_GAME__.scene.isActive('Game'));
 const retry=await page.evaluate(()=>{const s=window.__SURVIVOR_GAME__.scene.getScene('Game');s.paused=true;s.physics.pause();return {fog:s.mapManager.view.fog.length,wisps:s.mapManager.view.wisps.length,mood:s.mapManager.view.mood,terrain:s.children.list.filter(o=>o.name==='map:terrain').length,textures:Object.keys(s.textures.list).filter(k=>k.startsWith('mv-')).length,bosses:s.bosses.activeBosses.length};});assert.equal(retry.fog,8);assert.equal(retry.wisps,12);assert.equal(retry.mood,'quiet');assert.equal(retry.terrain,36);assert.equal(retry.textures,initial.textures);assert.equal(retry.bosses,0);
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>{const r=document.querySelector('canvas').getBoundingClientRect();return r.width<=390&&r.height<=844;});const mobile=await page.locator('canvas').boundingBox();assert.ok(mobile.width<=390&&mobile.height<=844);await page.screenshot({path:'map-previews/mobile.png'});assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);
 console.log(JSON.stringify({result:'PASS',initial,encounters,spawn,performanceResult,frameComparison:{rendered,oldGrid: hidden},combat,retry,mobile,errors,missing}));
}finally{await browser?.close();await server.close();}
